#!/usr/bin/env bash
# Configures a new ubuntu machine by installing
# Nginx where it should be listening on port 80
# Serve a page that would return a Hello World string
# Configures the nginx server to have a custom 404 page
# that contains the string 'Ceci n'est pas une page'.

apt-get update -y -qq
apt-get install nginx -y

# starting nginx service
service nginx start

# allowing nginx on firewall
ufw allow 'Nginx HTTP'

# Give the user ownership to website files for easy editing
chown -R "$USER":"$USER" /var/www/html
chmod -R 755 /var/www

# Backup default index
cp /var/www/html/index.nginx-debian.html /var/www/html/index.nginx-debian.html.bckp

# Creating new index
echo -e "Hello World!" > /var/www/html/index.nginx-debian.html

# Setting up /redirect_me to a youtube video
sed -i '24i\       rewrite ^/redirect_me https://www.youtube.com/watch?v=QH2-TGUlwu4 permanent;' /etc/nginx/sites-available/default

# Setting up custom 404 page
echo -e "Ceci n'est pas une page" > /var/www/html/404.html
sed -i 's/#error_page 404 \/404.html;/error_page 404 \/404.html;/' /etc/nginx/sites-available/default

# Restarting nginx
service nginx restart