#!/usr/bin/env bash
# This script configures nginx so that its http response
# contains the header "X-Served-By" with the value of
# the hostname of the server that served the request.
# This is useful for debugging purposes.

# Install nginx
sudo apt-get update
sudo apt-get install -y nginx

# Create a new configuration file
sudo cp /vagrant/nginx.conf /etc/nginx/sites-available/default

# Restart nginx
sudo service nginx restart

# Done
