#!/usr/bin/env bash
# This script has an infinite loop which resists the SIGTERM signal

invincible() {
	echo "I am invincible!!!"
}

trap invincible SIGTERM

while true; do
	echo "To infinity and beyond"
	sleep 2
done
