#!/usr/bin/env bash
# This script displays "Best School" 10 times but adds "Hi" at the 9th iteration

counter="0"
while [ $counter -lt "10" ]; do
        echo "Best School"
	if [ $counter -eq "8" ]; then
		echo "Hi"
	fi
        ((counter++))
done

