#!/usr/bin/env bash
# This script gets Apache to run on a docker container and
# return a page containing 'Hello Holberton' when querying
# the container on port 8080

sudo apt-get update
sudo apt-get install apache2 -y

sudo service apache2 start

echo "Hello Holberton" > /var/www/html/index.html
