#!/usr/bin/env bash
# This script gets Apache to run on a docker container and
# return a page containing 'Hello Holberton' when querying
# the container on port 8080

echo "ServerName localhost" >> /etc/apache2.conf
sudo service apache2 start